version: '2'

services:
    web:
        build: .
        ports:
            - 80:80

        environment:
            REDISTOGO_URL: redis://redis:6379
            MONGOHQ_URL: mongo://mongodb:27017

        links:
            - redis
            - mongodb

    redis:
        image: redis

    mongodb:
        image: mongo
